apiVersion: v1
kind: Service
metadata:
  name: lankmailintegration-service
spec:
  selector:
    app: lankmailintegration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
