name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      
          
      - name: Build the .NET application
        run: dotnet build -c Release

      - name: Substitute variables in appsettings.json
        run: |
            sed -i "s/\${DB_SERVER}/${{ secrets.DB_SERVER }}/g" ./app/appsettings.json
            sed -i "s/\${DB_PORT}/${{ secrets.DB_PORT }}/g" ./app/appsettings.json
            sed -i "s/\${DB_USERNAME}/${{ secrets.DB_USERNAME }}/g" ./app/appsettings.json
            sed -i "s/\${DB_PASSWORD}/${{ secrets.DB_PASSWORD }}/g" ./app/appsettings.json
            sed -i "s/\${DB_NAME}/${{ secrets.DB_NAME }}/g" ./app/appsettings.json
            sed -i "s/\${EMAIL_REMETENTE}/${{ secrets.EMAIL_REMETENTE }}/g" ./app/appsettings.json
            sed -i "s/\${EMAIL_DESTINATARIO}/${{ secrets.EMAIL_DESTINATARIO }}/g" ./app/appsettings.json
            sed -i "s/\${EMAIL_COPIA}/${{ secrets.EMAIL_COPIA }}/g" ./app/appsettings.json
            sed -i "s/\${EMAIL_SMTP}/${{ secrets.EMAIL_SMTP }}/g" ./app/appsettings.json
            sed -i "s/\${EMAIL_PORTA}/${{ secrets.EMAIL_PORTA }}/g" ./app/appsettings.json

      - name: Show replaced appsettings.json
        run: cat ./app/appsettings.json

      - name: Publish the .NET application
        run: dotnet publish -c Release -o ./app

      

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: willfjr86/lankmailintegration:latest
