name: Deploy HML

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Build the .NET application
        run: dotnet build -c Release

      - name: Publish the .NET application
        run: dotnet publish -c Release -o ./app

      - name: Substitute variables in appsettings.Staging.json
        run: |
            sed -i "s/\${DB_SERVER}/${{ secrets.DB_SERVER }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${DB_PORT}/${{ secrets.DB_PORT }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${DB_USERNAME}/${{ secrets.DB_USERNAME }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${DB_PASSWORD}/${{ secrets.DB_PASSWORD }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${DB_NAME}/${{ secrets.DB_NAME }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${EMAIL_REMETENTE}/${{ secrets.EMAIL_REMETENTE }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${EMAIL_HML_DESTINATARIO}/${{ secrets.EMAIL_HML_DESTINATARIO }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${EMAIL_COPIA}/${{ secrets.EMAIL_COPIA }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${EMAIL_SMTP}/${{ secrets.EMAIL_SMTP }}/g" ./app/appsettings.Staging.json
            sed -i "s/\${EMAIL_PORTA}/${{ secrets.EMAIL_PORTA }}/g" ./app/appsettings.Staging.json

      - name: Show replaced appsettings.Staging.json
        run: cat ./app/appsettings.Staging.json

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: willfjr86/lankmailintegrationhml:latest

  merge_to_master:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow == 'Deploy HML' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge develop into master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
          git checkout master
          git merge --ff-only origin/develop
          git push origin master
